### PR TITLE
Adding the invalid_challenge and request_failure hooks

### PR DESCRIPTION
**Pull request by nkovacne**
To us it is very useful to know when a challenge has failed (we use the dns-01 method and sometimes it fails because TXT DNS record has not propagated yet), so I created the "invalid_challenge" hook. This way we are aware and can act accordingly.

### CODE REVIEW

**Comment by lukas2511** [comment]
Can you please have a look at what you have done with docs/hook_chain.md, looks like you duplicated some of the text.

**Comment by nkovacne** [comment]
I just added a hook chain example that involves an invalid challenge, so the new hook gets called. If you think it is improper I will remove that.
```
+ + Challenge is invalid!
￼ +HOOK: invalid_challenge lukas.im the_reason
```

**Comment by lukas2511** [comment]
The diff shows that you readded the whole block with your change, but the old one is still there, so now the text is duplicated.

**Comment by nkovacne** [comment]
Oops, you're right, sorry, bad place for that example. I guess the example in examples/hook.sh should be enough.

**Comment by nkovacne** [comment]
I also added another hook: request_failure, in case the curl call should fail for some reason. The http_request() function already has a hook call (clean_challenge), but it is not exclusive for the request failure as clean_challenge is also called from other places where the request was ok.

Up until now we've got some 50X codes, so it's good to us to know when this happens and, in case failure extends in time, to be aware that something is not working good (probably on the client's server side).

**Comment by lukas2511** [comment]
The commits with this pull request got way to messed up. Can you please clean up your commits and also please create a separate pullrequest for the second hook? In this current state I don't want to merge it.

**Comment by nkovacne** [comment]
Sure, I'll tidy up code and create separate PRs.

**Pull request closed without merging**
