### PR TITLE
Added new feature Update registration contact #239

### PR DESCRIPTION
**Pull request by lukavia**

### CODE REVIEW

**Comment by lukas2511** [comment]
Definitively needs some more work, but is a good starting point.

Why do you check the value of `$FAILED` just after setting it, this will always be true, seems completely unnecessary and makes the code harder to read. 
Some parameters need to be in quotes (especially for that `mv` command at the end). 
Errors should be redirected to stderr, ideally using `_exiterr`. 
For temporary files (NEW_ACCOUNT_KEY_JSON) please use `_mktemp`. 
Maybe writing a backup file for the old json would be a good idea, in case something went wrong that wasn't catched anywhere. 
A bit more information for the user on what is going on would be nice, as far as I can see this code only really logs anything on errors, but a "Updating account information..." message or something similar would be nice.

**Comment by lukavia** [comment]
Re: `$FAILED` You are correct. I've copy-paste from the Init function and left it for polishing later. Fixed now. 
I've quoted parameters where appropriate.
Used _exitcode for exiting with error
Used _mktemp for temporary file
Make a backup file if the new one differs from the old one and don't touch anything otherwise
Added information to the user what is happening

**Comment by lukavia** [comment]
Hey, do you need anything else in this pull request?

**Comment by lukas2511** [comment]
@lukavia hey, sorry, i know it's been a while, i'm a bit busy but i'll look into your changes soon (hopefully later this week)

**Comment by lukas2511** [comment]
Thanks for the feature, I just merged it in commit ec1599e3b66582da471a70e0fb02fecdeaae4b31. Sorry that this took so long...

**Pull request closed without merging**
