### PR TITLE
Acme v02 api support

### PR DESCRIPTION
**Pull request by crza**
Account creation & updates work.
Certificate requests and domain validation are working.
Revocations are also supported.

Wildcard domains are not supported.
This seems to be a dehydrated limitation.

To use the new API:
  set API=2 and update CA endpoint.

### CODE REVIEW

**Comment by Eihrister** [comment]
@crza This line causes lines with *'s to be ignored:

```
[[ -z "${ZSH_VERSION:-}" ]] && shopt -s nullglob
```
With it commented out, it goes on further.. but for some reason I have a pending http-01 validation now, even though I have dns-01 configured.

**Comment by crza** [comment]
On my system this fix works, wildcard certificates are issued to my test-domain.

@Eihrister did you set CHALLENGETYPE="dns-01" ?

**Comment by crza** [comment]
fixed domain parser.

**Comment by Eihrister** [comment]
Hi @crza :)

Yeah, I'm sure that I'm using DNS-01, but perhaps that was a glitch while I was testing. However:

My hook script simply does not get any token for the wildcard host:

```
root@ca:/opt/dehydrated# ./dehydrated -c -x -d finalx.org -d www.finalx.org -d *.finalx.org
# INFO: Using main config file /opt/dehydrated/config
Processing finalx.org with alternative names: www.finalx.org *.finalx.org
 + Checking domain name(s) of existing cert... changed!
 + Domain name(s) are not matching!
 + Names in old certificate: finalx.org www.finalx.org
 + Configured names: *.finalx.org finalx.org www.finalx.org
 + Forcing renew.
 + Checking expire date of existing cert...
 + Valid till Apr 11 19:01:30 2018 GMT (Longer than 30 days). Ignoring because renew was forced!
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting challenges for finalx.org www.finalx.org...
*** HOOK SCRIPT - TOKEN RECEIVED FROM DEHYDRATED FOR: finalx.org
*** HOOK SCRIPT - TOKEN RECEIVED FROM DEHYDRATED FOR: www.finalx.org
 + Deploying challenges ...
 + Responding to challenge for finalx.org...
 + Challenge is valid!
 + Responding to challenge for www.finalx.org...
 + Challenge is valid!
 + Cleaning challenges ...
 + Requesting certificate...
 + Checking certificate...
 + Done!
 + Creating fullchain.pem...
 + Using cached chain!
 + Done!
root@ca:/opt/dehydrated#
```

And the generated certificate does not contain it:

```
root@ca:/opt/dehydrated# openssl x509 -text -noout -in certs/finalx.org/cert.pem | egrep '(Subject:|DNS:)'
        Subject: CN=finalx.org
                DNS:finalx.org, DNS:www.finalx.org
root@ca:/opt/dehydrated#
```

If I comment out the line I mentioned earlier, I get this:

```
root@ca:/opt/dehydrated# ./dehydrated -c -x -d finalx.org -d www.finalx.org -d *.finalx.org
# INFO: Using main config file /opt/dehydrated/config
Processing finalx.org with alternative names: www.finalx.org *.finalx.org
 + Checking domain name(s) of existing cert... changed!
 + Domain name(s) are not matching!
 + Names in old certificate: finalx.org www.finalx.org
 + Configured names: *.finalx.org finalx.org www.finalx.org
 + Forcing renew.
 + Checking expire date of existing cert...
 + Valid till Apr 11 19:04:22 2018 GMT (Longer than 30 days). Ignoring because renew was forced!
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting challenges for finalx.org www.finalx.org *.finalx.org...
ERROR: Can't retrieve challenges ({"identifier": {"type": "dns", "value": "finalx.org"}, "status": "invalid", "expires": "2018-01-18T20:01:42Z", "challenges": [{"type": "dns-01", "status": "invalid", "error": {"type": "urn:ietf:params:acme:error:unauthorized", "detail": "Incorrect TXT record \"542VKJwpzIFScQzHwr_UuAi7RIQnfNfaKr60uNQXjmk\" found at _acme-challenge.finalx.org", "status": 403}, "url": "https://acme-staging-v02.api.letsencrypt.org/acme/challenge/XTGNapp9Zc0ushAmVn_wNrqUZ_GMde7gFVbHod8KAQs/91703011", "token": "ZulD6CnNde22IDuUSNwtXm2Ebi5viUqC8KBXOtf9KZA", "keyAuthorization": "ZulD6CnNde22IDuUSNwtXm2Ebi5viUqC8KBXOtf9KZA.CNPp1qbfrUo5zq4DfqVkEDZZewBDfH9tMXLFVyW-KSo"}], "wildcard": true})
root@ca:/opt/dehydrated#
```

Or, prettified:

```json
{
  "identifier": {
    "type": "dns",
    "value": "finalx.org"
  },
  "status": "invalid",
  "expires": "2018-01-18T20:01:42Z",
  "challenges": [
    {
      "type": "dns-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:unauthorized",
        "detail": "Incorrect TXT record \"542VKJwpzIFScQzHwr_UuAi7RIQnfNfaKr60uNQXjmk\" found at _acme-challenge.finalx.org",
        "status": 403
      },
      "url": "https://acme-staging-v02.api.letsencrypt.org/acme/challenge/XTGNapp9Zc0ushAmVn_wNrqUZ_GMde7gFVbHod8KAQs/91703011",
      "token": "ZulD6CnNde22IDuUSNwtXm2Ebi5viUqC8KBXOtf9KZA",
      "keyAuthorization": "ZulD6CnNde22IDuUSNwtXm2Ebi5viUqC8KBXOtf9KZA.CNPp1qbfrUo5zq4DfqVkEDZZewBDfH9tMXLFVyW-KSo"
    }
  ],
  "wildcard": true
}
```

In any case, it's supposed to have two tokens for finalx.org, one for the normal host and one for the wildcard? Maybe I'll spend some time debugging tomorrow.

**Comment by crza** [comment]
letsencrypt seems to query _acme-challenge.finalx.org instead of _acme-challenge.*.finalx.org
2 problems:
 - TTL of previous challenge for finalx.org might cause problems
 - dehydrated / hook script sends *.finalx.org, which is not checked.

**Comment by lukas2511** [comment]
Thanks! After some testing that old stuff still worked I merged this in 68cb1e066111eb80433ee8f8c1d8c35f84fff9b1.

I didn't yet test the ACME v02 implementation, but I'm taking your word that it's working and as long as nothing else breaks it's at least a great start. There definitively is some more cleanup and lots of testing required until this is ready for a release, but for now it will be in the master branch.

I had to fix domains.txt parsing (3e521e1c0128d67473ad0c77641b68fb974b4cbb) but it should now working normally and also accept wildcard domains.

The DNS thingy... It would be easy to just remove the prefix when calling the hook, or just leave it to the hook script to handle the wildcard... Shouldn't be much code but maybe it would be nice to allow for both ways, a simple config switch would be good for that.

**Pull request closed without merging**
