### PR TITLE
Dockerfile: Add Docker support

### PR DESCRIPTION
**Pull request by jmreicha**
Adds the necessary dependencies and files to a Dockerfile so the dehydrated script can be run inside a container.

### CODE REVIEW

**Comment by Rayne** [comment]
See https://github.com/lukas2511/dehydrated/pull/286

**Comment by jmreicha** [comment]
I added a [wiki page](https://github.com/lukas2511/dehydrated/wiki/Docker-support).

I'm curious why nobody wants Docker support?

**Comment by extremeshok** [comment]
Because its utterly useless. Obviously you drank too much of the docker cool-aid.

Dehydrate is a simple script, there is no need to use it as a docker.  It also relies on a webserver or a dnsserver to fullfill the request, so your docker image is invalid for practical points.

**Comment by jmreicha** [comment]
That was incredibly rude.  I was just asking a question.

**Comment by extremeshok** [comment]
@jmreicha that was me being nice, sorry if you were offended.

**Comment by lukas2511** [comment]
Just to clarify: I don't have nothing specific against a Dockerfile (although in this case I really don't see the point of running a simple script like this inside a container), I just don't want any kind of packaging files inside this repository for now.

If I'd start merging stuff like this I'd end up with a repository with Dockerfiles, Vagrantfiles, puppet playbooks, chef cookbooks, Debian package files, rpm package files, PKGBUILD for archlinux, ebuild file for gentoo, lxc example config, freebsd package files, nixos package files, ... and I don't want that. Especially because I'd have to update most of them every time I do a new release.

**Comment by jmreicha** [comment]
@lukas2511 That makes sense, I appreciate the explanation.

**Pull request closed without merging**
