### PR TITLE
Debianized

### PR DESCRIPTION
**Pull request by Vitexus**
Hallo, 
there is files required for building basic debian package for dehydrated

Thank for your work!

### CODE REVIEW

**Comment by ezbik** [comment]
@Vitexus According to cron file, it is executed under root? Unprivileged user should be used instead, I believe.

**Comment by ezbik** [comment]
@Vitexus /var/www/letsencrypt  should be changed to /var/lib/letsencrypt, because it may interfere with user's other files in /var/www

**Comment by lukas2511** [comment]
dehydrated is already in the debian package tree (stretch and sid) and I won't add package files to this repository, thanks anyway.

**Comment by leonklingele** [comment]
Why not use the packaging which is already available in the Debian repos? https://packages.debian.org/search?keywords=letsencrypt.sh

**Comment by Vitexus** [comment]
Sorry man my mistake :)

**Pull request closed without merging**
